contact/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contact, name="contact"),
]

mylinks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from core import views
from core.views import LinkCreate, LinkUpdate, LinkDelete, CategoryCreate, CategoryUpdate, CategoryDelete
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.links, name='home'),
    path('admin/', admin.site.urls),
    path('create/', login_required(LinkCreate.as_view()), name='create'),
    path('update/<int:pk>/', login_required(LinkUpdate.as_view()), name='update'),
    path('delete/<int:pk>/', login_required(LinkDelete.as_view()), name='delete'),
    path('create_category/', login_required(CategoryCreate.as_view()), name='create_category'),
    path('update_category/<int:pk>/', login_required(CategoryUpdate.as_view()), name='update_category'),
    path('delete_category/<int:pk>/', login_required(CategoryDelete.as_view()), name='delete_category'),

    # Paths de pages
    path('contact/', include('contact.urls')),
    
    # Paths de Auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

registration/urls.py
from django.urls import path
from .views import SignUpView, ProfileUpdate, EmailUpdate

urlpatterns = [
    path('signup/', SignUpView.as_view(), name="register"),
    path('profile/', ProfileUpdate.as_view(), name="profile"),
    path('profile/email/', EmailUpdate.as_view(), name="profile_email"),
]

contact/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models
from registration.models import Profile

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name= "Categoría", null=False, blank=False) 
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, null=False, blank=False) 

    class Meta:
        verbose_name= "Categoría"
    
    def __str__(self):
        return self.name

class Link(models.Model):
    name = models.CharField( max_length=100, verbose_name= "Sitio", null=False, blank=False) 
    text = models.TextField(verbose_name= "Descripción corta", null=True, blank=True)  
    link = models.URLField(verbose_name= "Url", default=None, max_length=500, null=False, blank=False) 
    img= models.ImageField(verbose_name= "Imagen", upload_to="logo", null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=False, blank=False) 
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, null=False, blank=False) 

    class Meta:
        verbose_name= "Sitio"
    
    def __str__(self):
        return self.name

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label="Nombre", required=True, widget=forms.TextInput(
        attrs={'class':'form-control', 'placeholder':'Escribe tu nombre'}
    ), min_length=3, max_length=100)
    email = forms.EmailField(label="Email", required=True, widget=forms.EmailInput(
        attrs={'class':'form-control', 'placeholder':'Escribe tu email'}
    ), min_length=3, max_length=100)
    content = forms.CharField(label="Contenido", required=True, widget=forms.Textarea(
        attrs={'class':'form-control', 'rows': 3, 'placeholder':'Escribe tu mensaje'}
    ), min_length=10, max_length=1000)
    

core/forms.py
from django import forms
from django.contrib.auth.models import User
from core.models import Link, Category


class LinkForm(forms.ModelForm):
    class Meta:
        model= Link
        fields= ['name', 'text', 'link', 'img', 'category', 'user']
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'text': forms.TextInput(attrs={'class':'form-control'}),
            'link': forms.TextInput(attrs={'class':'form-control'}),   
            'img': forms.FileInput(attrs={'class':'form-control'}),
            'category': forms.Select(attrs={'class':'form-control'}),
            'user': forms.Select(attrs={'class':'form-control'}),

        }

        labels = {
                'name':'Nombre', 'text': 'Descripcion', 'link':'URL sitio',
            }

class CategoryForm(forms.ModelForm):
        class Meta:
            model= Category
            fields= ['name', 'user']
            widgets = {
                'name': forms.TextInput(attrs={'class':'form-control'}),
                'user': forms.Select(attrs={'class':'form-control'}),

            }

            labels = {
                    'name':'Nombre', 
                }

class LinkUpdateForm(forms.ModelForm):
    class Meta:
        model= Link
        fields= ['name', 'text', 'link', 'img', 'category']
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'text': forms.TextInput(attrs={'class':'form-control'}),
            'link': forms.TextInput(attrs={'class':'form-control'}),   
            'img': forms.FileInput(attrs={'class':'form-control'}),
        }
        labels = {
                'name':'', 'text': '', 'link':'', 'img': ''
            }

class CategoryUpdateForm(forms.ModelForm):
        class Meta:
            model= Category
            fields= ['name']
            widgets = {
                'name': forms.TextInput(attrs={'class':'form-control'}),
            }

            labels = {
                    'name':'', 
                }

contact/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.mail import EmailMessage
from .forms import ContactForm


def contact(request):
    contact_form = ContactForm()
    if request.method == "POST":
        contact_form = ContactForm(data=request.POST)
        if contact_form.is_valid():
            name = request.POST.get('name', '')
            email = request.POST.get('email', '')
            content = request.POST.get('content', '')

            # Creamos el correo
            email = EmailMessage(
                "Mensaje enviado desde Link'Collection Board",
                "De {} <{}>\n\nEscribió:\n\n{}".format(name, email, content),
                "no-contestar@inbox.mailtrap.io",
                ['fswd.cmc@gmail.com'],
                reply_to=[email]
            )

            # Lo enviamos y redireccionamos
            try:
                email.send()
                # Todo ha ido bien, redireccionamos a OK
                return redirect(reverse('contact')+"?ok")
            except:
                # Algo no ha ido bien, redireccionamos a FAIL
                return redirect(reverse('contact')+"?fail")
    
    return render(request, "contact/contact.html",{'form':contact_form})

    

core/views.py
from django.shortcuts import render
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from core.models import Category, Link
from registration.models import Profile
from .forms import LinkForm, CategoryForm, LinkUpdateForm, CategoryUpdateForm
from django.urls import reverse_lazy

# Create your views here.
def links(request):    
    links= Link.objects.all()
    return render(request, "core/link_list.html", {'links':links})

class LinkCreate(CreateView):
    model= Link
    form_class= LinkForm  
    template_name = "core/create.html"

    def get_success_url(self):
        return reverse_lazy('home') + '?created' 


class LinkUpdate(UpdateView):
    model= Link
    form_class= LinkUpdateForm 
    template_name = "core/update.html"

    def get_success_url(self):
        return reverse_lazy('home') + '?ok'  


class LinkDelete(DeleteView):
    model= Link
    template_name = "core/confirm_delete.html"

    def get_success_url(self):
        return reverse_lazy('home') + '?deleted'  


class CategoryCreate(CreateView):
    model= Category
    form_class= CategoryForm  
    template_name = "core/create_category.html"

    def get_success_url(self):
        return reverse_lazy('home') + '?createdc' 


class CategoryUpdate(UpdateView):
    model= Category
    form_class= CategoryUpdateForm 
    template_name = "core/update_category.html"

    def get_success_url(self):
        return reverse_lazy('home') + '?ok'  


class CategoryDelete(DeleteView):
    model= Category
    template_name = "core/confirm_delete_category.html"

    def get_success_url(self):
        return reverse_lazy('home') + '?deleted'  

contact/templates/contact/contact.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Contact{% endblock %}

{% block content %}

<!-- Formulario de contacto -->
<div class="container text-align-left col-sm-11 col-md-6 box">
  <h3>Contactanos</h3><br>
  {% if 'ok' in request.GET %}
      <p><b>Su mensaje se ha enviado correctamente, en breve nos pondremos en contacto con usted.</b></p>
  {% endif %}
  <form action="" method="POST">
      {% csrf_token %}
      <div class="form-group">
          <div class="input-group">
              {{form.name}}
          </div>
          {{form.name.errors}}
      </div>
      <div class="form-group">
          <div class="input-group">
              {{form.email}}
          </div>
          {{form.email.errors}}
      </div>
      <div class="form-group">
          <div class="input-group">
              {{form.content}}
          </div>
          {{form.content.errors}}
      </div>
      <div class="text-center">
          <input type="submit" class="btn btn-primary btn-block py-2" value="Enviar">
      </div>
  </form>
</div>

{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap, Jquery, Css -->  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <!-- Link CSS -->
    {% load static %}
    <link href="{% static 'css/master.css' %}" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css" integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">

  </head>

  <body id="demo">

    <nav>
      <div class="row text-center">        
        {% if request.user.is_authenticated %}
          {% if request.user.is_superuser %}
            <a class="nav-link col-3" href="/admin">Admin {{request.user}}</a>
          {% else %} 
            <a class="nav-link col-3" href="/">Hi {{request.user}}!</a>
          {% endif %}
          <a class="nav-link col-3" href="/accounts/profile">Account</a>
          <a class="nav-link col-3" href="/contact">Contact</a>
          <a class="nav-link col-3" href="/accounts/logout">Logout</a>
          {% for pro in profiles %}
            {% if request.user == pro.user %}
              {% if pro.darkmode == True %}
                <script>
                  document.getElementById("demo").style.backgroundColor = "#222222";
                  document.getElementById("demo").style.color = "white";
                  document.getAttribute("a").style.
                </script>
              {% else %}
                <script>
                  document.getElementById("demo").style.backgroundColor = "white";
                  document.getElementById("demo").style.color = "#222222";
                </script>     
              {% endif %}
            }

            {% endif %}
          {% endfor %}
        {% else %}       
          <a class="nav-link col-3" href="/">Home</a>
          <a class="nav-link col-3" href="/accounts/signup">Signup</a>
          <a class="nav-link col-3" href="/accounts/login">Login</a>
          <a class="nav-link col-3" href="/contact">Contact</a>

        {% endif %}
      </div>
    </nav>

<div class="middle col-12">
  {% block content %}{% endblock %}
</div>

{% comment %}
<a href="">Doname un 
  <i class="fas fa-coffee"></i>
</a>
{% endcomment %}
  </body>
</html>

core/templates/core/confirm_delete.html
{% extends 'core/base.html' %}

{% block title %}Borrar Sitio{% endblock %}

{% block content %}

<div class="container text-align-left col-sm-11 col-md-4 box">
    <h3>Eliminar sitio</h3>
    <form action="" method="post">{% csrf_token %}
        <p>¿Seguro quieres borrar a <b>"{{ object }}"</b>?</p>
        <input type="submit" class="btn home container text-center col-sm-12 col-md-6 btn-block" value="Confirmar"/>
        <a href="{% url 'home' %}">   
            <p class= " text-center mt-3">No, volver</p>
        </a>
    </form>
</div> 
{% endblock %}

core/templates/core/confirm_delete_category.html
{% extends 'core/base.html' %}

{% block title %}Borrar Categoría{% endblock %}

{% block content %}

<div class="container text-align-left col-sm-11 col-md-4 box">
    <h3>Eliminar categoría</h3>
    <form action="" method="post">{% csrf_token %}
        <p>Si elimina la categoría <b>"{{ object }}"</b>, se eliminarán automáticamente los sitios asociados. ¿Seguro desea eliminarla?</p>
        <input type="submit" class="btn home container text-center col-sm-12 col-md-6 btn-block" value="Confirmar" />
        <a href="{% url 'home' %}">   
            <p class= " text-center mt-3">No, volver</p>
        </a>
    </form>
</div> 
{% endblock %}

core/templates/core/create.html
{% extends 'core/base.html' %}

{% block title %}Crear sitio{% endblock %}

{% block content %}

<div class="container text-align-left col-sm-11 col-md-6 box">
    <h3>Agregar nuevo sitio web</h3><br>

    <form id="form_creacion" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="container col-12">            
            <input type="text" name="name" class="form-control" placeholder="Nombre del sitio" maxlength="100" id="id_name" required ><br>            
            <input type="text" name="text" class="form-control" placeholder="Descripción corta (opcional)" id="id_text"><br>
            <input type="text" name="link" class="form-control" placeholder="URL del sitio. Ej: www.google.com" maxlength="500" id="id_link" required >
        <label for="id_img">Imagen del sitio:</label>
            <input type="file" name="img" class="form-control" accept="image/*" id="id_img">
        <label for="id_category">Categoría:</label>
        <select name="category" class="form-control" id="id_category" required>
            <option value="" selected>---------</option>
            {% for c in categories %}
                {% if c.user == request.user.profile %}     
                    <option value="{{c.id}}">{{c}}</option>
                {% endif %}              
            {% endfor %}
        </select>
        <select name="user" class="form-control" id="id_user" hidden>
            <option value="" >---------</option>
            <option selected value="{{request.user.profile.id}}">{{request.user.profile}}</option>
        </select><br>                     
        </table>        
        <div class="col-12 p-0 m-0 mt-3">
            <input type="submit" class="btn container col-sm-12 col-md-6  btn-block" value="Crear" />
            <p class= " text-center mt-3">
                Si desea volver, haz click <a href="/">aquí.</a> <br> Si desea añadir una nueva categoría,<a href="/create_category">aquí.</a>
            </p>
        </div>                  
    </form>
</div>

{% endblock %}

core/templates/core/create_category.html
{% extends 'core/base.html' %}

{% block title %}Crear categoría{% endblock %}

{% block content %}

<div class="container text-align-left col-sm-11 col-md-6 box">
    <h3>Añadir nueva categoría</h3><br>
    <form id="form_creacion" action="" method="POST">
        {% csrf_token %}
        <table class="container col-12">
            <label for="id_user">Nueva categoría:</label>
            <input type="text" name="name" class="form-control" maxlength="100" placeholder="Ej: Redes sociales..." required id="id_name">

            <select name="user" class="form-control" id="id_user" hidden>
                <option value="" >---------</option>
                <option selected value="{{request.user.profile.id}}">{{request.user.profile}}</option>
            </select> <br>
        </table>        
        <div class="col-12 p-0 m-0 mt-3">
            <input type="submit" class="btn container col-sm-12 col-md-6  btn-block" value="Crear" />
            <p class= " text-center mt-3">
                Si desea volver, haz click <a href="/">aquí.</a> <br> Si desea añadir un nuevo sitio,<a href="/create">aquí.</a>
            </p>
        </div>                  
    </form>
</div>

{% endblock %}

core/templates/core/link_list.html
{% extends 'core/base.html' %}

{% block title %}Links{% endblock %}

{% block content %}

<div class="row text-center col-12">
  {% if request.user.is_authenticated %}  
  <a class="col-4 float-left" href="/create">+ Agregar nuevo sitio</a>
    <a class="col-4 float-left" href="/create_category">+ Agregar nueva categoria</a>
  <div class="container col-10 mt-4">
    {% for cat in categories %}
    {% if cat.user == request.user.profile %}        
        <div class="row cat mb-5">
          <h3 class="container col-10 float-left ml-0">
            <abrr title="Edit category">
              <a href="{% url 'update_category' cat.id %}" class="edit">
                {{cat.name}}
              </a>
            </abrr>
          </h3> 
          <h3 class="container col-2 float-right">     
            <a href="{% url 'delete_category' cat.id %}" class="edit float-right">
              <abrr title="Delete category">
                <i class="fas fa-times"></i>                      
              </abrr>
            </a>
          </h3>           
          {% for lk in links %}
            {% if lk.category == cat %}
            <div class="float-left col-2 p-3">
                <a href="{{lk.link}}">
                  <abrr title="{{lk.text}}">
                    {% if lk.img %}
                    <img src="{{lk.img.url}}" alt="">
                    {% else %}  
                    {% load static %}
                    <img src="{% static '/none.jpg' %}" alt="">
                    {% endif %}               
                  </abrr>
                </a>
                <p class="mt-1">
                  <abrr title="Edit {{lk.name}}">                    
                    <a href="{% url 'update' lk.id %}">
                      {{lk.name}} 
                    </a>   
                  </abrr>
                </p>
              </div>  
            {% endif %}                
            {% endfor %}          
        </div>
        {% endif %}
    {% endfor %}      
  </div>        
  
  
  {% else %}  
  <div class="container col-10 mt-0">    
    <h1 class="welcome">
      Hi! welcome to  <br>the collections board
    </h1>
  </div>
  {% endif %}
</div>

{% endblock %}


{% if 'ok' in request.GET %}
<p style="color:green;">
  El sitio se ha actualizado correctamente.
</p>
{% elif 'created' in request.GET %}
<p style="color:green;">
  Se ha añadido un nuevo sitio.
</p>
{% elif 'createdc' in request.GET %}
<p style="color:green;">
Se ha añadido una nueva categoría.
</p>
{% elif 'deleted' in request.GET %}
<p style="color:green;">
  El sitio se ha eliminado correctamente.
</p>
{% endif %} 

core/templates/core/update.html
{% extends 'core/base.html' %}

{% block title %}Actualizar Sitio{% endblock %}

{% block content %} 

<div class="container text-align-left col-sm-11 col-md-4 box">
    <h3>Editar sitio web</h3> 
    <a href="{% url 'delete' link.id %}">
        ¿Quieres eliminar el sitio?             
    </a><br><br>
    <form id="form_creacion" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="container col-12">
            {{form.name}} <br>
            {{form.text}} <br>
            {{form.link}} <br>
            {{form.img}} <br>
            <select name="category" class="form-control" id="id_category" required>
            {% for c in categories %}
                {% if c.user == request.user.profile %}     
                    <option value="{{c.id}}">{{c}}</option>
                {% endif %}              
            {% endfor %}
            </select> <br>
        </table>
        <div class="col-12">
            <input type="submit" class="btn home container col-sm-12 col-md-6 btn-block" value="Actualizar" />
            <a href="{% url 'home' %}">   
                <p class= " text-center mt-3">Volver</p>                 
            </a>            
        </div>  
    </form>
</div>  
{% endblock %}

core/templates/core/update_category.html
{% extends 'core/base.html' %}

{% block title %}Actualizar Sitio{% endblock %}

{% block content %} 

<div class="container text-align-left col-sm-11 col-md-4 box">
    <h3>Editar categoría</h3> <br>
    <form id="form_creacion" action="" method="POST">
        {% csrf_token %}
        <table class="container col-12">
            {{form.as_table}}
        </table><br>
        <div class="col-12">
            <input type="submit" class="btn home container col-sm-12 col-md-6 btn-block" value="Actualizar" />
            <a href="{% url 'home' %}">   
                <p class= " text-center mt-3">Volver</p>
            </a>            
        </div>  
    </form>
</div>  
{% endblock %}